[PRODUCTION]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    DOVEADM_BIN = '/usr/bin/doveadm'

[TESTING]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    DOVEADM_BIN = '/usr/bin/doveadm'

[DEVELOPMENT]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    DOVEADM_BIN = '/usr/bin/doveadm'
