[PRODUCTION]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    DOVEADM_BIN = '/usr/bin/doveadm'
    [PRODUCTION.LOGGING]
    LOGLEVEL = 'INFO'
    LOG_TO_FILE = false
    LOGFILE = '/var/log/ddmail_dmcp_keyhandler.log'
    LOG_TO_SYSLOG = true
    SYSLOG_SERVER = '/dev/log'

[TESTING]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    DOVEADM_BIN = '/usr/bin/doveadm'
    [TESTING.LOGGING]
    LOGLEVEL = 'DEBUG'
    LOG_TO_FILE = true
    LOGFILE = '/var/log/ddmail_dmcp_keyhandler.log'
    LOG_TO_SYSLOG = false
    SYSLOG_SERVER = '/dev/log'

[DEVELOPMENT]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    DOVEADM_BIN = '/usr/bin/doveadm'
    [DEVELOPMENT.LOGGING]
    LOGLEVEL = 'DEBUG'
    LOG_TO_FILE = true
    LOGFILE = '/var/log/ddmail_dmcp_keyhandler.log'
    LOG_TO_SYSLOG = false
    SYSLOG_SERVER = '/dev/log'
